behaviors:
  MoveToTargetAgent:
    trainer_type: ppo
    # trainer_settings:
    #   batch_size: 64
    #   buffer_size: 1024
  # Add any other settings you need
    summary_freq: 1000 # This will log every 1000 steps
    hyperparameters:
      batch_size: 32
      buffer_size: 640
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    max_steps: 5000000
    checkpoint_interval: 100000

    #   learning_rate_schedule: constant
    #   batch_size: 64
    #   buffer_size: 50000
    #   buffer_init_steps: 0
    #   tau: 0.005
    #   steps_per_update: 10.0
    #   save_replay_buffer: false
    #   init_entcoef: 0.01
    #   reward_signal_steps_per_update: 10.0
    # network_settings:
    #   normalize: false
    #   hidden_units: 20
    #   num_layers: 2
    #   vis_encode_type: simple
    # reward_signals:
    #   extrinsic:
    #     gamma: 0.99
    #     strength: 1.0
    # keep_checkpoints: 5
